[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/seed/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
